# generated by datamodel-codegen:
#   filename:  cancel_auction.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class CancelAuctionParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    ca_asset_contract: str
    ca_asset_id: str
