# generated by datamodel-codegen:
#   filename:  finish_auction.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class FinishAuctionParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    fa_asset_contract: str
    fa_asset_id: str
    fa_asset_seller: str
