# generated by datamodel-codegen:
#   filename:  start_auction.json

from __future__ import annotations

from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class AuctionArgsOriginFee(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class AuctionArgsPayout(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class SaAuction(BaseModel):
    class Config:
        extra = Extra.forbid

    auction_args_sell_asset_amount: str
    auction_args_buy_asset_type: str
    auction_args_buy_asset: str
    auction_args_start_time: Optional[str]
    auction_args_duration: str
    auction_args_minimal_price: str
    auction_args_buy_out_price: str
    auction_args_minimal_step: str
    auction_args_max_seller_fees: str
    auction_args_origin_fees: List[AuctionArgsOriginFee]
    auction_args_payouts: List[AuctionArgsPayout]
    auction_args_data_type: Optional[str]
    auction_args_data: Optional[str]


class StartAuctionParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    sa_asset_contract: str
    sa_asset_token_id: str
    sa_auction: SaAuction
