from enum import Enum


class AssetClassEnum(str, Enum):
    ETH = 'ETH'
    XTZ = 'XTZ'
    FUNGIBLE_TOKEN = 'TEZOS_FT'
    NON_FUNGIBLE_TOKEN = 'TEZOS_NFT'
    MULTI_TOKEN = 'TEZOS_MT'
    ERC20 = 'ERC20'
    ERC721 = 'ERC721'
    ERC1155 = 'ERC1155'
    ERC721_LAZY = 'ERC721_LAZY'
    ERC1155_LAZY = 'ERC1155_LAZY'
    COLLECTION = 'COLLECTION'
    GEN_ART = 'GEN_ART'
