# generated by datamodel-codegen:
#   filename:  accept_floor_bid.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from pydantic import Extra


class AfbOriginFee(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class AfbPayout(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class AcceptFloorBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    afb_asset_contract: str
    afb_asset_token_id: str
    afb_bidder: str
    afb_bid_type: str
    afb_bid_asset: str
    afb_origin_fees: List[AfbOriginFee]
    afb_payouts: List[AfbPayout]
