# generated by datamodel-codegen:
#   filename:  accept_bid.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from pydantic import Extra


class AbOriginFee(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class AbPayout(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class AcceptBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    ab_asset_contract: str
    ab_asset_token_id: str
    ab_bidder: str
    ab_bid_type: str
    ab_bid_asset: str
    ab_origin_fees: List[AbOriginFee]
    ab_payouts: List[AbPayout]
