# generated by datamodel-codegen:
#   filename:  cancel_bid.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class CancelBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    cb_asset_contract: str
    cb_asset_token_id: str
    cb_bid_type: str
    cb_bid_asset: str
