# generated by datamodel-codegen:
#   filename:  put_floor_bid.json

from __future__ import annotations

from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class BidOriginFee(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class BidPayout(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class PfbBid(BaseModel):
    class Config:
        extra = Extra.forbid

    bid_origin_fees: List[BidOriginFee]
    bid_payouts: List[BidPayout]
    bid_amount: str
    bid_asset_qty: str
    bid_expiry_date: Optional[str]
    bid_data_type: Optional[str]
    bid_data: Optional[str]


class PutFloorBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    pfb_asset_contract: str
    pfb_bid_type: str
    pfb_bid_asset: str
    pfb_bid: PfbBid
