# generated by datamodel-codegen:
#   filename:  put_bid.json

from __future__ import annotations

from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class BidOriginFee(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class BidPayout(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class PbBid(BaseModel):
    class Config:
        extra = Extra.forbid

    bid_origin_fees: List[BidOriginFee]
    bid_payouts: List[BidPayout]
    bid_amount: str
    bid_asset_qty: str
    bid_expiry_date: Optional[str]
    bid_data_type: Optional[str]
    bid_data: Optional[str]


class PutBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    pb_asset_contract: str
    pb_asset_token_id: str
    pb_bid_type: str
    pb_bid_asset: str
    pb_bid: PbBid
