# generated by datamodel-codegen:
#   filename:  sell.json

from __future__ import annotations

from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class BidOriginFee(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class BidPayout(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class PBBid(BaseModel):
    class Config:
        extra = Extra.forbid

    bid_origin_fees: List[BidOriginFee]
    bid_payouts: List[BidPayout]
    bid_amount: str
    bid_asset_qty: str
    bid_data_type: Optional[str]
    bid_data: Optional[str]


class PutBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    pb_asset_contract: str
    pb_asset_token_id: str
    pb_bid_type: str
    pb_bid_asset: str
    pb_bid: PBBid


class PutFloorBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    pfb_asset_contract: str
    pfb_bid_type: str
    pfb_bid_asset: str
    pfb_bid: PBBid


class AcceptBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    ab_asset_contract: str
    ab_asset_token_id: str
    ab_bidder: str
    ab_bid_type: str
    ab_bid_asset: str
    ab_origin_fees: List[BidOriginFee]
    ab_payouts: List[BidPayout]


class AcceptFloorBidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    afb_asset_contract: str
    afb_asset_token_id: str
    afb_bidder: str
    afb_bid_type: str
    afb_bid_asset: str
    afb_origin_fees: List[BidOriginFee]
    afb_payouts: List[BidPayout]
