# generated by datamodel-codegen:
#   filename:  fulfill_ask.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class FulfillAskParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    ask_id: str
    proxy: Optional[str]
