# generated by datamodel-codegen:
#   filename:  offer.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class OfferParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    creator: str
    objkt_id: str
    price: str
    royalties: str
