# generated by datamodel-codegen:
#   filename:  buy.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class BuyParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    b_asset_contract: str
    b_asset_token_id: str
    b_seller: str
    b_sale_type: str
    b_sale_asset: str
    b_buyer: str
