# generated by datamodel-codegen:
#   filename:  buy.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from pydantic import Extra


class BOriginFee(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class BPayout(BaseModel):
    class Config:
        extra = Extra.forbid

    part_account: str
    part_value: str


class BuyParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    b_asset_contract: str
    b_asset_token_id: str
    b_seller: str
    b_sale_type: str
    b_sale_asset: str
    b_amount: str
    b_origin_fees: List[BOriginFee]
    b_payouts: List[BPayout]
